### ISSUE TITLE
motorStart IC

### ISSUE THREAD

**Issue by IamDamian69** [modelleicher/FS22_simpleIC#12]
Hello, I have a question, is there a chance for simpleIC to have motorstart working because I tried to make it work in 22 but it won't work, Thanks!

**Comment by modelleicher** [comment]
Hello, currently no. In the future, probably. Need to get the basic script working absolutely bug-free before adding new features I made that mistake in 19 and had so many issues ;)

**Comment by IamDamian69** [comment]
Oh, I understand, thanks for the answer.
