### ISSUE TITLE
SimpleIC fixed to work with no errors on FS v1.4.1

### ISSUE THREAD

**Issue by ebelbeb** [modelleicher/FS22_simpleIC#13]
Hi, I had to move the registration of specializations from registerSimpleIC.lua to modDesc.xml. Now SimpleIC works fine on FS v1.4.1:
https://youtu.be/-EKSPsBVP0U
I followed the tips from this forum: https://forum.giants-software.com/viewtopic.php?f=895&t=190799&p=1500889#p1500889

**Comment by modelleicher** [comment]
Hi, this is not neccesary SimpleIC works fine with Patch 1.4.1 without any changes. registerSimpleIC.lua uses a method of registration that wasn't affected by the Patch changes ;)
