### ISSUE TITLE
Not working in cab

### ISSUE THREAD

**Issue by devriesthymon** [modelleicher/FS22_simpleIC#14]
As said in the title I can't get Simple IC to work in the cab view, it works when I'm outside of the vehicle. I use Courseplay and Autodrive which may be related to the problem. Already tried some different settings for controls but it doens't seem to help.

**Comment by ebelbeb** [comment]
Check if you have set the key to activate SimpleIC inside the vehicle.

**Comment by devriesthymon** [comment]
I have set it on the left mouse button. I have tried different configurations but that doesn't seem to help. I also don't see the X's when in cab view.

**Comment by ebelbeb** [comment]
After entering the vehicle, you first need to activate SimpleIC, only then will you be able to see and use the triggers (x's). Check in-game key bindings, look for SimpleIC section and redefine the key for activation. The default key should be \, set the same key again.

**Comment by devriesthymon** [comment]
I've done that. Nothing changes when pressing the on/off button. Also when outside the vehicle I still see the markers after pressing the button.

**Comment by ebelbeb** [comment]
The SimpleIC activation key only works inside the vehicle. 
SimpleIC is always active on the outside of the vehicle.

**Comment by ebelbeb** [comment]
https://user-images.githubusercontent.com/69918710/168146241-df4e1245-0a52-43df-bf2f-50f3b9ab2e64.mp4

**Comment by ebelbeb** [comment]
Try temporarily moving all your mods to a different folder. 
Next just copy SimpleIC and one mod that uses SimpleIC to mods folder.

**Comment by devriesthymon** [comment]
I went into a savegame with only simpleIC+tractor, it worked then. And when I load into my normal savegame now it also works. Thanks for your help!

**Comment by ebelbeb** [comment]
I'm glad I could help :)
