### ISSUE TITLE
Einstellungen ändern ohne Admin-Rechte / Einstellungen speichern

### ISSUE THREAD

**Issue by jason0611** [modelleicher/FS22_simpleIC#20]
Hallo Modelleicher,

zunächst vielen Dank für SimpleIC: Das ist eines der Skripts, die für mich aus dem LS nicht mehr wegzudenken sind.

Zwei Dinge haben mich allerdings etwas gestört: Zum einen ist im MP die Admin-Rolle erforderlich, um die Einstellungen zu ändern, und zum anderen werden die getätigten Einstellungen nicht gespeichert und müssen jedes Mal neu getätigt werden.

Da ich in der letzten Woche etwas Zeit hatte, habe ich dem Skript eine Funktion zum Speichern und Laden der Einstellungen hinzugefügt und die Einstellungen im Spielmenü in den Bereich "Allgemeine Einstellungen" verschoben, weil dieser auch ohne Admin-Rolle im Spiel aufrufbar ist.

Alle Änderungen sind in der registerSimpleIC.lua, wenn Du Interesse daran hast, stelle ich sie Dir gerne hier oder via Pull-Request zur Verfügung. Bitte verstehe es nicht als Einmischerei in Deine Skripte: Ich sehe einfach, dass Du sehr beschäftigt bist mit ebenfalls wichtigen Themen und Mods und möchte daher ein kleines bisschen unterstützen.

Viele Grüße,
Martin

**Comment by modelleicher** [comment]
Moin, kannst du mir gerne zukommen lassen wenn alles funktioniert und du nichts dagegen hast würd ich das dann in die nächste Version übernehmen :) 
Das speichern der Einstellungen war schon lange auf der Liste dessen was ich gerne umgesetzt hätte, das andere klingt auch vernünftig.

>>Bitte verstehe es nicht als Einmischerei in Deine Skripte
Da hab ich nix dagegen sofern das vernünftig gemacht ist und die Sinnhaftigkeit der Änderungen plausibel erklärt werden kann, im Gegenteil.. Wie du sagst ich hab immer viel zu tun und viele Projekte gleichzeitig da wär ich blöd mich über Hilfe zu beschweren  ;)

LG

**Comment by jason0611** [comment]
Ein Pull-Request macht keinen Sinn, es würde die ganze Entwicklung- und Testhistorie hochgeladen und synchronisiert. Daher lieber auf diesem Weg: [registerSimpleIC.txt](https://github.com/modelleicher/FS22_simpleIC/files/8903458/registerSimpleIC.txt)

**Comment by modelleicher** [comment]
Danke! :) 

Ja da muss ich gestehen hab ich nicht so wirklich raus wie das auf Github genau funktioniert oder wie man das aufsetzt/einstellt dass man da die Hilfe anderer vernünftig einpflegen kann.. :D
