### ISSUE TITLE
Mauszeiger

### ISSUE THREAD

**Issue by Bandesss** [modelleicher/FS22_simpleIC#33]
Hallo wenn wir Simpel IC benutzen geht am Server die maus weg in der Karte
Gibt's da noch nen Fix ?
Danke für den Mod

**Comment by modelleicher** [comment]
Habt ihr auch die aktuellste Version im Einsatz? Das war mal früher ein Bug den hab ich aber gefixt

**Comment by Bandesss** [comment]
Den von hier also ja

**Comment by modelleicher** [comment]
Zeig mal die Log

**Comment by Bandesss** [comment]
Keine Fehler vorhanden, haben den Mod simpel Ic weg gemacht und haben keinen Fehler mehr mit der Maus

Mit freundlichem Grüßen
Ronny Bandmann

------------------------------------
Ronny Bandmann
Im Grün 4

72712 Sulz am Neckar
-------------------------------------
Am 11. Jan. 2023, 20:54 +0100 schrieb modelleicher ***@***.***>:

**Comment by modelleicher** [comment]
Ohne Log gehts hier nicht weiter :D

**Comment by Bandesss** [comment]
Ok ich kann meine jungs nicht schon wieder nerven alles gut.
Danke dir trotzdem
