### ISSUE TITLE
LUA Error in Mulitplayer Game on server

### ISSUE THREAD

**Issue by Resthirnverstaerker** [modelleicher/FS22_simpleIC#8]
Hi,
not sure if this is related to the other MP issue already reported, so I created another ticket.

Error in Server-log on server (SQuote):
Error: Running LUA method 'packetReceived'.
dataS/scripts/network/Server.lua(486) : attempt to call method 'readStream' (a nil value)

Error in Client-log on local machine:
Error: Running LUA method 'packetReceived'.

-Error occurs when joining game server while snychronization between client and server
-Error occurs when clicking some SIC trigger ingame

SIC Version: 0.9.0.2

Files attached:
-Logfile gameserver
-Logfile local client

[Server-log.txt](https://github.com/modelleicher/FS22_simpleIC/files/8418280/Server-log.txt)
[Client-log.txt](https://github.com/modelleicher/FS22_simpleIC/files/8418283/Client-log.txt)

**Comment by modelleicher** [comment]
Hi, please retest with current Version 0.9.0.4 if error still occurs :)

**Comment by Resthirnverstaerker** [comment]
Fix confirmed - error no longer occurs
Tested version: v0.9.0.5

Thanks!
